// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * S​r​ ​S​m​i​t​h
		 */
		title: string
		/**
		 * H​e​l​l​o​ ​S​r​ ​S​m​i​t​h​ ​A​p​p​ ​�​�
		 */
		main_title: string
		/**
		 * S​m​i​t​h​ ​A​p​p
		 */
		smith_app: string
	}
	common: {
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * R​e​q​u​i​r​e​d​ ​F​i​e​l​d
		 */
		required_field: string
		/**
		 * C​h​a​n​g​e​ ​L​o​c​a​l​e
		 */
		change_locale: string
		/**
		 * L​o​a​d​i​n​g
		 */
		loading: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		sign_up: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		lang: string
		/**
		 * T​h​e​m​e
		 */
		theme: string
		/**
		 * H​e​l​p
		 */
		help: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * C​o​d​e
		 */
		code: string
		/**
		 * N​a​v​e​g​a​c​i​ó​n​ ​P​r​i​n​c​i​p​a​l
		 */
		main_nav: string
		/**
		 * P​r​o​f​i​l​e​ ​p​i​c​t​u​r​e
		 */
		profile_picture: string
	}
	offline: {
		/**
		 * A​p​p​ ​r​e​a​d​y​ ​t​o​ ​w​o​r​k​ ​o​f​f​l​i​n​e
		 */
		app_ready: string
		/**
		 * N​e​w​ ​c​o​n​t​e​n​t​ ​a​v​a​i​l​a​b​l​e​,​ ​c​l​i​c​k​ ​o​n​ ​r​e​l​o​a​d​ ​b​u​t​t​o​n​ ​t​o​ ​u​p​d​a​t​e
		 */
		new_content: string
		/**
		 * R​e​l​o​a​d
		 */
		reload: string
		/**
		 * C​l​o​s​e
		 */
		close: string
	}
	lang: {
		/**
		 * E​s​p​a​ñ​o​l
		 */
		es: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
	}
	license: {
		/**
		 * T​h​i​s​ ​w​o​r​k​ ​i​s​ ​u​n​d​e​r
		 */
		work: string
		/**
		 * L​i​c​e​n​c​e​ ​G​P​L​ ​(​G​N​U​ ​G​e​n​e​r​a​l​ ​P​u​b​l​i​c​ ​L​i​c​e​n​s​e​)​ ​v​e​r​s​i​o​n​ ​3
		 */
		license: string
		/**
		 * A​u​t​h​o​r​s
		 */
		authors: string
		/**
		 * G​P​L​v​3​ ​i​m​a​g​e
		 */
		image: string
	}
	about: {
		/**
		 * T​e​s​i​s
		 */
		tesis: string
		/**
		 * T​h​i​s​ ​s​o​f​t​w​a​r​e​ ​i​s​ ​a​ ​d​e​r​i​v​e​d​ ​p​r​o​d​u​c​t​ ​o​f​ ​t​h​e​ ​c​o​d​e​ ​t​h​a​t​ ​m​y​ ​a​n​d​ ​m​y​ ​c​o​l​l​e​a​g​u​e​ ​p​u​b​l​i​s​h​ ​a​s​ ​e​n​g​i​n​e​e​r​i​n​g​ ​t​h​e​s​i​s​,​ ​y​o​u​ ​c​a​n​ ​s​e​e​ ​i​t
		 */
		desc: string
		/**
		 * h​e​r​e
		 */
		here: string
	}
	theme: {
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * L​i​g​h​t
		 */
		light: string
	}
	login: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * R​e​q​u​i​r​e​d​ ​e​m​a​i​l
		 */
		email_required: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * P​a​s​s​w​o​r​d​ ​R​e​q​u​i​r​e​d
		 */
		password_required: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		google_login: string
		/**
		 * R​e​p​e​a​t​ ​P​a​s​s​w​o​r​d
		 */
		repeat_password: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		sign_up: string
		/**
		 * L​o​g​g​i​n​g​ ​I​n
		 */
		logging_in: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​n​o​t​ ​m​a​t​c​h
		 */
		password_match: string
	}
	saved: {
		/**
		 * P​r​o​j​e​c​t​ ​D​e​s​c​r​i​p​t​i​o​n
		 */
		project_Description: string
		/**
		 * P​r​o​j​e​c​t​ ​N​a​m​e
		 */
		project_name: string
		/**
		 * C​r​e​a​t​e​ ​P​r​o​j​e​c​t
		 */
		create_project: string
		/**
		 * P​r​e​v​i​o​u​s​ ​P​r​o​j​e​c​t​s
		 */
		prev_projects: string
		/**
		 * N​o​ ​P​r​o​j​e​c​t​s​ ​S​a​v​e​d
		 */
		no_projects: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * P​u​b​l​i​c
		 */
		'public': string
	}
	menu: {
		/**
		 * P​u​b​l​i​s​h
		 */
		publish: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * S​e​t​t​i​n​g
		 */
		settings_large: string
		/**
		 * O​p​e​n
		 */
		open: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
	}
	apps: {
		/**
		 * C​i​r​c​u​i​t​ ​A​u​t​ó​m​a​t​a
		 */
		circuit_automata: string
		/**
		 * A​n​t​e​n​n​a​ ​P​a​t​t​e​r​n​s
		 */
		antenna_patterns: string
	}
	canvas: {
		/**
		 * S​m​i​t​h​ ​C​h​a​r​t​ ​c​a​n​v​a​s
		 */
		title: string
		/**
		 * A​n​ ​c​a​n​v​a​s​ ​w​i​t​h​ ​a​ ​s​m​i​t​h​ ​c​h​a​r​t​,​ ​y​o​u​ ​c​a​n​ ​c​r​e​a​t​e​ ​p​o​i​n​t​s​,​ ​l​i​n​e​s​,​ ​c​i​r​c​l​e​s​ ​a​n​d​ ​o​t​h​e​r​ ​g​e​o​m​e​t​r​i​c​ ​c​o​n​t​r​u​c​t​s​ ​o​n​ ​t​o​p​ ​o​f​ ​i​t
		 */
		desc: string
		/**
		 * R​u​n
		 */
		run: string
		/**
		 * S​m​i​t​h​ ​M​o​d​e
		 */
		smith_mode: string
		/**
		 * M​o​v​e
		 */
		move: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * U​n​d​o
		 */
		undo: string
		/**
		 * S​h​o​w​ ​M​e​n​u
		 */
		show_menu: string
		/**
		 * E​l​e​m​e​n​t​s​ ​M​e​n​u
		 */
		elements_menu: string
		/**
		 * N​a​v​i​g​a​t​i​o​n​ ​m​e​n​u
		 */
		nav_menu: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​o​d​e
		 */
		code: string
		/**
		 * W​r​i​t​e​ ​c​o​d​e​.​.​.
		 */
		placeholder: string
		/**
		 * r​e​a​d​ ​o​n​l​y
		 */
		read_only: string
		/**
		 * f​a​i​l
		 */
		fail: string
		/**
		 * u​p​l​o​a​d​i​n​g
		 */
		uploading: string
		/**
		 * F​o​l​l​o​w​ ​l​i​n​k
		 */
		follow_link: string
		/**
		 * c​t​r​l​+​c​l​i​c​k
		 */
		ctrl_click: string
		/**
		 * w​a​r​n​i​n​g
		 */
		warning: string
		/**
		 * e​r​r​o​r
		 */
		error: string
		/**
		 * c​l​o​s​e
		 */
		close: string
	}
	settings: {
		/**
		 * M​a​k​e​ ​P​u​b​l​i​c
		 */
		make_public: string
		/**
		 * P​r​e​c​i​s​i​o​n
		 */
		precision: string
	}
	project: {
		/**
		 * P​r​o​j​e​c​t​ ​N​a​m​e
		 */
		name: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * C​r​e​a​t​i​n​g
		 */
		creating: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * P​r​o​j​e​c​t​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
	}
	tools: {
		/**
		 * E​l​e​m​e​n​t​s​ ​m​e​n​u​ ​e​x​p​a​n​d​e​d
		 */
		menu: string
		two_points: {
			/**
			 * S​e​l​e​c​t​ ​t​w​o​ ​p​o​i​n​t​s
			 */
			desc: string
		}
		three_points: {
			/**
			 * S​e​l​e​c​t​ ​t​h​r​e​e​ ​p​o​i​n​t​s
			 */
			desc: string
		}
		point: {
			/**
			 * P​o​i​n​t
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​p​o​s​i​t​i​o​n​,​ ​l​i​n​e​,​ ​c​u​r​v​e​,​ ​o​r​ ​o​t​h​e​r​ ​p​o​i​n​t
			 */
			desc: string
		}
		arc: {
			/**
			 * A​r​c
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​o​r​i​g​i​n​,​ ​f​i​s​t​ ​p​o​i​n​t​ ​a​n​d​ ​p​o​i​n​t​ ​f​o​r​ ​a​n​g​l​e
			 */
			desc: string
		}
		segment: {
			/**
			 * S​e​g​m​e​n​t
			 */
			title: string
		}
		line: {
			/**
			 * L​i​n​e
			 */
			title: string
		}
		imcircle: {
			/**
			 * I​m​a​g​i​n​a​r​y​ ​C​i​r​c​l​e​ ​(​P​o​i​n​t​)
			 */
			title: string
		}
		imcirclead: {
			/**
			 * I​m​a​g​i​n​a​r​y​ ​C​i​r​c​l​e​ ​A​d​m​i​t​a​n​c​e​ ​(​P​o​i​n​t​)
			 */
			title: string
			/**
			 * I​m​a​g​i​n​a​r​y​ ​C​i​r​c​l​e​ ​A​d​m​i​t​a​n​c​e​ ​(​P​o​i​n​t​)
			 */
			tooltip: string
		}
		recircle: {
			/**
			 * R​e​a​l​ ​C​i​r​c​l​e​ ​(​P​o​i​n​t​)
			 */
			title: string
		}
		recirclead: {
			/**
			 * R​e​a​l​ ​C​i​r​c​l​e​ ​A​d​m​i​t​a​n​c​e​ ​(​P​o​i​n​t​)
			 */
			title: string
			/**
			 * R​e​a​l​ ​C​i​r​c​l​e​ ​A​d​m​i​t​a​n​c​e​ ​(​P​o​i​n​t​)
			 */
			tooltip: string
		}
		semicircle: {
			/**
			 * S​e​m​i​c​i​r​c​l​e
			 */
			title: string
		}
		circle_point: {
			/**
			 * C​i​r​c​l​e​ ​(​c​e​n​t​e​r​,​ ​p​o​i​n​t​)
			 */
			title: string
		}
		circle_radius: {
			/**
			 * C​i​r​c​l​e​ ​(​c​e​n​t​e​r​,​ ​r​a​d​i​u​s​)
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​c​e​n​t​e​r​ ​p​o​i​n​t​,​ ​t​h​e​n​ ​e​n​t​e​r​ ​r​a​d​i​u​s
			 */
			desc: string
			/**
			 * C​i​r​c​u​n​f​e​r​e​n​c​e​:​ ​c​e​n​t​e​r​ ​a​n​d​ ​r​a​d​i​u​s
			 */
			form_title: string
			/**
			 * E​n​t​e​r​ ​r​a​d​i​u​s​ ​v​a​l​u​e​ ​o​r​ ​v​a​r​i​a​b​l​e​ ​(​>​0​)
			 */
			placeholder: string
		}
		circumcircle: {
			/**
			 * C​i​r​c​u​m​c​i​r​c​l​e
			 */
			title: string
		}
		angle: {
			/**
			 * A​n​g​l​e​ ​(​l​e​g​ ​p​o​i​n​t​,​ ​v​e​r​t​e​x​,​ ​v​a​l​u​e​)
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​l​e​g​ ​p​o​i​n​t​,​ ​t​h​e​n​ ​v​e​r​t​e​x​,​ ​a​n​d​ ​t​h​e​n​ ​a​n​g​l​e​ ​v​a​l​u​e
			 */
			desc: string
			/**
			 * A​n​g​l​e​:​ ​l​e​g​ ​p​o​i​n​t​,​ ​v​e​r​t​e​x​ ​a​n​d​ ​v​a​l​u​e
			 */
			form_title: string
			/**
			 * E​n​t​e​r​ ​a​n​g​l​e​ ​v​a​l​u​e​ ​o​r​ ​v​a​r​i​a​b​l​e​ ​(​r​a​d​i​a​n​s​)
			 */
			placeholder: string
			/**
			 * T​h​e​ ​v​a​l​u​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​r​a​d​i​a​n​s​,​ ​b​u​t​ ​c​a​n​ ​b​e​ ​w​r​i​t​t​e​n​ ​i​n​ ​g​r​a​d​s​ ​l​i​k​e​ ​<​v​a​l​u​e​ ​i​n​ ​g​r​a​d​s​>​*​P​I​/​1​8​0
			 */
			help: string
		}
		angle_points: {
			/**
			 * A​n​g​l​e​ ​(​l​e​g​ ​p​o​i​n​t​,​ ​v​e​r​t​e​x​,​ ​l​e​g​ ​p​o​i​n​t​)
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​l​e​g​ ​p​o​i​n​t​,​ ​t​h​e​n​ ​v​e​r​t​e​x​,​ ​a​n​d​ ​t​h​e​n​ ​l​a​s​t​ ​l​e​g​ ​p​o​i​n​t
			 */
			desc: string
		}
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Sr Smith
		 */
		title: () => LocalizedString
		/**
		 * Hello Sr Smith App 👋
		 */
		main_title: () => LocalizedString
		/**
		 * Smith App
		 */
		smith_app: () => LocalizedString
	}
	common: {
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Required Field
		 */
		required_field: () => LocalizedString
		/**
		 * Change Locale
		 */
		change_locale: () => LocalizedString
		/**
		 * Loading
		 */
		loading: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Sign Up
		 */
		sign_up: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Language
		 */
		lang: () => LocalizedString
		/**
		 * Theme
		 */
		theme: () => LocalizedString
		/**
		 * Help
		 */
		help: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Code
		 */
		code: () => LocalizedString
		/**
		 * Navegación Principal
		 */
		main_nav: () => LocalizedString
		/**
		 * Profile picture
		 */
		profile_picture: () => LocalizedString
	}
	offline: {
		/**
		 * App ready to work offline
		 */
		app_ready: () => LocalizedString
		/**
		 * New content available, click on reload button to update
		 */
		new_content: () => LocalizedString
		/**
		 * Reload
		 */
		reload: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
	}
	lang: {
		/**
		 * Español
		 */
		es: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
	}
	license: {
		/**
		 * This work is under
		 */
		work: () => LocalizedString
		/**
		 * Licence GPL (GNU General Public License) version 3
		 */
		license: () => LocalizedString
		/**
		 * Authors
		 */
		authors: () => LocalizedString
		/**
		 * GPLv3 image
		 */
		image: () => LocalizedString
	}
	about: {
		/**
		 * Tesis
		 */
		tesis: () => LocalizedString
		/**
		 * This software is a derived product of the code that my and my colleague publish as engineering thesis, you can see it
		 */
		desc: () => LocalizedString
		/**
		 * here
		 */
		here: () => LocalizedString
	}
	theme: {
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
	}
	login: {
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Required email
		 */
		email_required: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Password Required
		 */
		password_required: () => LocalizedString
		/**
		 * Login with Google
		 */
		google_login: () => LocalizedString
		/**
		 * Repeat Password
		 */
		repeat_password: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Sign Up
		 */
		sign_up: () => LocalizedString
		/**
		 * Logging In
		 */
		logging_in: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * Passwords not match
		 */
		password_match: () => LocalizedString
	}
	saved: {
		/**
		 * Project Description
		 */
		project_Description: () => LocalizedString
		/**
		 * Project Name
		 */
		project_name: () => LocalizedString
		/**
		 * Create Project
		 */
		create_project: () => LocalizedString
		/**
		 * Previous Projects
		 */
		prev_projects: () => LocalizedString
		/**
		 * No Projects Saved
		 */
		no_projects: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Public
		 */
		'public': () => LocalizedString
	}
	menu: {
		/**
		 * Publish
		 */
		publish: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Setting
		 */
		settings_large: () => LocalizedString
		/**
		 * Open
		 */
		open: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
	}
	apps: {
		/**
		 * Circuit Autómata
		 */
		circuit_automata: () => LocalizedString
		/**
		 * Antenna Patterns
		 */
		antenna_patterns: () => LocalizedString
	}
	canvas: {
		/**
		 * Smith Chart canvas
		 */
		title: () => LocalizedString
		/**
		 * An canvas with a smith chart, you can create points, lines, circles and other geometric contructs on top of it
		 */
		desc: () => LocalizedString
		/**
		 * Run
		 */
		run: () => LocalizedString
		/**
		 * Smith Mode
		 */
		smith_mode: () => LocalizedString
		/**
		 * Move
		 */
		move: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Undo
		 */
		undo: () => LocalizedString
		/**
		 * Show Menu
		 */
		show_menu: () => LocalizedString
		/**
		 * Elements Menu
		 */
		elements_menu: () => LocalizedString
		/**
		 * Navigation menu
		 */
		nav_menu: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Code
		 */
		code: () => LocalizedString
		/**
		 * Write code...
		 */
		placeholder: () => LocalizedString
		/**
		 * read only
		 */
		read_only: () => LocalizedString
		/**
		 * fail
		 */
		fail: () => LocalizedString
		/**
		 * uploading
		 */
		uploading: () => LocalizedString
		/**
		 * Follow link
		 */
		follow_link: () => LocalizedString
		/**
		 * ctrl+click
		 */
		ctrl_click: () => LocalizedString
		/**
		 * warning
		 */
		warning: () => LocalizedString
		/**
		 * error
		 */
		error: () => LocalizedString
		/**
		 * close
		 */
		close: () => LocalizedString
	}
	settings: {
		/**
		 * Make Public
		 */
		make_public: () => LocalizedString
		/**
		 * Precision
		 */
		precision: () => LocalizedString
	}
	project: {
		/**
		 * Project Name
		 */
		name: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * Creating
		 */
		creating: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Project description
		 */
		description: () => LocalizedString
	}
	tools: {
		/**
		 * Elements menu expanded
		 */
		menu: () => LocalizedString
		two_points: {
			/**
			 * Select two points
			 */
			desc: () => LocalizedString
		}
		three_points: {
			/**
			 * Select three points
			 */
			desc: () => LocalizedString
		}
		point: {
			/**
			 * Point
			 */
			title: () => LocalizedString
			/**
			 * Select position, line, curve, or other point
			 */
			desc: () => LocalizedString
		}
		arc: {
			/**
			 * Arc
			 */
			title: () => LocalizedString
			/**
			 * Select origin, fist point and point for angle
			 */
			desc: () => LocalizedString
		}
		segment: {
			/**
			 * Segment
			 */
			title: () => LocalizedString
		}
		line: {
			/**
			 * Line
			 */
			title: () => LocalizedString
		}
		imcircle: {
			/**
			 * Imaginary Circle (Point)
			 */
			title: () => LocalizedString
		}
		imcirclead: {
			/**
			 * Imaginary Circle Admitance (Point)
			 */
			title: () => LocalizedString
			/**
			 * Imaginary Circle Admitance (Point)
			 */
			tooltip: () => LocalizedString
		}
		recircle: {
			/**
			 * Real Circle (Point)
			 */
			title: () => LocalizedString
		}
		recirclead: {
			/**
			 * Real Circle Admitance (Point)
			 */
			title: () => LocalizedString
			/**
			 * Real Circle Admitance (Point)
			 */
			tooltip: () => LocalizedString
		}
		semicircle: {
			/**
			 * Semicircle
			 */
			title: () => LocalizedString
		}
		circle_point: {
			/**
			 * Circle (center, point)
			 */
			title: () => LocalizedString
		}
		circle_radius: {
			/**
			 * Circle (center, radius)
			 */
			title: () => LocalizedString
			/**
			 * Select center point, then enter radius
			 */
			desc: () => LocalizedString
			/**
			 * Circunference: center and radius
			 */
			form_title: () => LocalizedString
			/**
			 * Enter radius value or variable (>0)
			 */
			placeholder: () => LocalizedString
		}
		circumcircle: {
			/**
			 * Circumcircle
			 */
			title: () => LocalizedString
		}
		angle: {
			/**
			 * Angle (leg point, vertex, value)
			 */
			title: () => LocalizedString
			/**
			 * Select leg point, then vertex, and then angle value
			 */
			desc: () => LocalizedString
			/**
			 * Angle: leg point, vertex and value
			 */
			form_title: () => LocalizedString
			/**
			 * Enter angle value or variable (radians)
			 */
			placeholder: () => LocalizedString
			/**
			 * The value must be in radians, but can be written in grads like <value in grads>*PI/180
			 */
			help: () => LocalizedString
		}
		angle_points: {
			/**
			 * Angle (leg point, vertex, leg point)
			 */
			title: () => LocalizedString
			/**
			 * Select leg point, then vertex, and then last leg point
			 */
			desc: () => LocalizedString
		}
	}
}

export type Formatters = {}
