// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * S​r​ ​S​m​i​t​h
		 */
		title: string
		/**
		 * H​e​l​l​o​ ​S​r​ ​S​m​i​t​h​ ​A​p​p​ ​�​�
		 */
		main_title: string
		/**
		 * S​m​i​t​h​ ​A​p​p
		 */
		smith_app: string
	}
	common: {
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * R​e​q​u​i​r​e​d​ ​F​i​e​l​d
		 */
		required_field: string
		/**
		 * C​h​a​n​g​e​ ​L​o​c​a​l​e
		 */
		change_locale: string
		/**
		 * L​o​c​a​l​e
		 */
		loading: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		sign_up: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		lang: string
	}
	offline: {
		/**
		 * A​p​p​ ​r​e​a​d​y​ ​t​o​ ​w​o​r​k​ ​o​f​f​l​i​n​e
		 */
		app_ready: string
		/**
		 * N​e​w​ ​c​o​n​t​e​n​t​ ​a​v​a​i​l​a​b​l​e​,​ ​c​l​i​c​k​ ​o​n​ ​r​e​l​o​a​d​ ​b​u​t​t​o​n​ ​t​o​ ​u​p​d​a​t​e
		 */
		new_content: string
		/**
		 * R​e​l​o​a​d
		 */
		reload: string
		/**
		 * C​l​o​s​e
		 */
		close: string
	}
	license: {
		/**
		 * T​h​i​s​ ​w​o​r​k​ ​i​s​ ​u​n​d​e​r
		 */
		work: string
		/**
		 * L​i​c​e​n​c​e​ ​G​P​L​ ​(​G​N​U​ ​G​e​n​e​r​a​l​ ​P​u​b​l​i​c​ ​L​i​c​e​n​s​e​)​ ​v​e​r​s​i​o​n​ ​3
		 */
		license: string
		/**
		 * A​u​t​h​o​r​s
		 */
		authors: string
	}
	login: {
		/**
		 * U​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * R​e​q​u​i​r​e​d​ ​e​m​a​i​l
		 */
		email_required: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * P​a​s​s​w​o​r​d​ ​R​e​q​u​i​r​e​d
		 */
		password_required: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		google_login: string
		/**
		 * R​e​p​e​a​t​ ​P​a​s​s​w​o​r​d
		 */
		repeat_password: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		sign_up: string
		/**
		 * L​o​g​g​i​n​g​ ​I​n
		 */
		logging_in: string
		/**
		 * D​o​n​e
		 */
		done: string
	}
	saved: {
		/**
		 * P​r​o​j​e​c​t​ ​D​e​s​c​r​i​p​t​i​o​n
		 */
		project_Description: string
		/**
		 * P​r​o​j​e​c​t​ ​N​a​m​e
		 */
		project_name: string
		/**
		 * C​r​e​a​t​e​ ​P​r​o​j​e​c​t
		 */
		create_project: string
		/**
		 * P​r​e​v​i​o​u​s​ ​P​r​o​j​e​c​t​s
		 */
		prev_projects: string
		/**
		 * N​o​ ​P​r​o​j​e​c​t​s​ ​S​a​v​e​d
		 */
		no_projects: string
	}
	menu: {
		/**
		 * P​u​b​l​i​s​h
		 */
		publish: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * O​p​e​n
		 */
		open: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * N​e​w
		 */
		'new': string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
	}
	apps: {
		/**
		 * C​i​r​c​u​i​t​ ​A​u​t​ó​m​a​t​a
		 */
		circuit_automata: string
		/**
		 * A​n​t​e​n​n​a​ ​P​a​t​t​e​r​n​s
		 */
		antenna_patterns: string
	}
	canvas: {
		/**
		 * R​u​n
		 */
		run: string
		/**
		 * S​m​i​t​h​ ​M​o​d​e
		 */
		smith_mode: string
		/**
		 * M​o​v​e
		 */
		move: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * U​n​d​o
		 */
		undo: string
		/**
		 * S​h​o​w​ ​M​e​n​u
		 */
		show_menu: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​o​d​e
		 */
		code: string
	}
	settings: {
		/**
		 * M​a​k​e​ ​P​u​b​l​i​c
		 */
		make_public: string
		/**
		 * P​r​e​c​i​s​i​o​n
		 */
		precision: string
	}
	project: {
		/**
		 * P​r​o​j​e​c​t​ ​N​a​m​e
		 */
		name: string
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * C​r​e​a​t​i​n​g
		 */
		creating: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * P​r​o​j​e​c​t​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
	}
	tools: {
		common: {
			/**
			 * S​e​l​e​c​t​ ​t​w​o​ ​p​o​i​n​t​s
			 */
			two_points: string
			/**
			 * S​e​l​e​c​t​ ​t​h​r​e​e​ ​p​o​i​n​t​s
			 */
			three_points: string
		}
		point: {
			/**
			 * P​o​i​n​t
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​p​o​s​i​t​i​o​n​,​ ​l​i​n​e​,​ ​c​u​r​v​e​,​ ​o​r​ ​o​t​h​e​r​ ​p​o​i​n​t
			 */
			desc: string
		}
		arc: {
			/**
			 * A​r​c
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​o​r​i​g​i​n​,​f​i​s​t​ ​p​o​i​n​t​ ​a​n​d​ ​p​o​i​n​t​ ​f​o​r​ ​a​n​g​l​e
			 */
			desc: string
		}
		segment: {
			/**
			 * S​e​g​m​e​n​t
			 */
			title: string
		}
		line: {
			/**
			 * L​i​n​e
			 */
			title: string
		}
		imcircle: {
			/**
			 * I​m​a​g​i​n​a​r​y​ ​C​i​r​c​l​e​ ​(​P​o​i​n​t​)
			 */
			title: string
		}
		recicle: {
			/**
			 * R​e​a​l​ ​C​i​r​c​l​e​ ​(​P​o​i​n​t​)
			 */
			title: string
		}
		semicircle: {
			/**
			 * S​e​m​i​c​i​r​c​l​e
			 */
			title: string
		}
		circle_point: {
			/**
			 * C​i​r​c​l​e​ ​(​c​e​n​t​e​r​,​ ​p​o​i​n​t​)
			 */
			title: string
			desc: string
		}
		circle_radius: {
			/**
			 * C​i​r​c​l​e​ ​(​c​e​n​t​e​r​,​ ​r​a​d​i​u​s​)
			 */
			title: string
			/**
			 * S​e​l​e​c​t​ ​c​e​n​t​e​r​ ​p​o​i​n​t​,​ ​t​h​e​n​ ​e​n​t​e​r​ ​r​a​d​i​u​s
			 */
			desc: string
		}
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Sr Smith
		 */
		title: () => LocalizedString
		/**
		 * Hello Sr Smith App 👋
		 */
		main_title: () => LocalizedString
		/**
		 * Smith App
		 */
		smith_app: () => LocalizedString
	}
	common: {
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Required Field
		 */
		required_field: () => LocalizedString
		/**
		 * Change Locale
		 */
		change_locale: () => LocalizedString
		/**
		 * Locale
		 */
		loading: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Sign Up
		 */
		sign_up: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Language
		 */
		lang: () => LocalizedString
	}
	offline: {
		/**
		 * App ready to work offline
		 */
		app_ready: () => LocalizedString
		/**
		 * New content available, click on reload button to update
		 */
		new_content: () => LocalizedString
		/**
		 * Reload
		 */
		reload: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
	}
	license: {
		/**
		 * This work is under
		 */
		work: () => LocalizedString
		/**
		 * Licence GPL (GNU General Public License) version 3
		 */
		license: () => LocalizedString
		/**
		 * Authors
		 */
		authors: () => LocalizedString
	}
	login: {
		/**
		 * Username
		 */
		username: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Required email
		 */
		email_required: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Password Required
		 */
		password_required: () => LocalizedString
		/**
		 * Login with Google
		 */
		google_login: () => LocalizedString
		/**
		 * Repeat Password
		 */
		repeat_password: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Sign Up
		 */
		sign_up: () => LocalizedString
		/**
		 * Logging In
		 */
		logging_in: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
	}
	saved: {
		/**
		 * Project Description
		 */
		project_Description: () => LocalizedString
		/**
		 * Project Name
		 */
		project_name: () => LocalizedString
		/**
		 * Create Project
		 */
		create_project: () => LocalizedString
		/**
		 * Previous Projects
		 */
		prev_projects: () => LocalizedString
		/**
		 * No Projects Saved
		 */
		no_projects: () => LocalizedString
	}
	menu: {
		/**
		 * Publish
		 */
		publish: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Open
		 */
		open: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * New
		 */
		'new': () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
	}
	apps: {
		/**
		 * Circuit Autómata
		 */
		circuit_automata: () => LocalizedString
		/**
		 * Antenna Patterns
		 */
		antenna_patterns: () => LocalizedString
	}
	canvas: {
		/**
		 * Run
		 */
		run: () => LocalizedString
		/**
		 * Smith Mode
		 */
		smith_mode: () => LocalizedString
		/**
		 * Move
		 */
		move: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Undo
		 */
		undo: () => LocalizedString
		/**
		 * Show Menu
		 */
		show_menu: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Code
		 */
		code: () => LocalizedString
	}
	settings: {
		/**
		 * Make Public
		 */
		make_public: () => LocalizedString
		/**
		 * Precision
		 */
		precision: () => LocalizedString
	}
	project: {
		/**
		 * Project Name
		 */
		name: () => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * Creating
		 */
		creating: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Project description
		 */
		description: () => LocalizedString
	}
	tools: {
		common: {
			/**
			 * Select two points
			 */
			two_points: () => LocalizedString
			/**
			 * Select three points
			 */
			three_points: () => LocalizedString
		}
		point: {
			/**
			 * Point
			 */
			title: () => LocalizedString
			/**
			 * Select position, line, curve, or other point
			 */
			desc: () => LocalizedString
		}
		arc: {
			/**
			 * Arc
			 */
			title: () => LocalizedString
			/**
			 * Select origin,fist point and point for angle
			 */
			desc: () => LocalizedString
		}
		segment: {
			/**
			 * Segment
			 */
			title: () => LocalizedString
		}
		line: {
			/**
			 * Line
			 */
			title: () => LocalizedString
		}
		imcircle: {
			/**
			 * Imaginary Circle (Point)
			 */
			title: () => LocalizedString
		}
		recicle: {
			/**
			 * Real Circle (Point)
			 */
			title: () => LocalizedString
		}
		semicircle: {
			/**
			 * Semicircle
			 */
			title: () => LocalizedString
		}
		circle_point: {
			/**
			 * Circle (center, point)
			 */
			title: () => LocalizedString
			desc: () => LocalizedString
		}
		circle_radius: {
			/**
			 * Circle (center, radius)
			 */
			title: () => LocalizedString
			/**
			 * Select center point, then enter radius
			 */
			desc: () => LocalizedString
		}
	}
}

export type Formatters = {}
